// Code Generated by Sidekick is for learning and experimentation purposes only.
const express = require('express');
const os = require('os');
const crypto = require('crypto');

const app = express();

app.disable('x-powered-by');
app.use(express.json());

const startedAt = Date.now();
const port = Number(process.env.PORT || 3000);
const version = process.env.APP_VERSION || 'local-dev';
const serviceName = process.env.SERVICE_NAME || 'Helm Artifact Promotion Demo';
const nodeEnv = process.env.NODE_ENV || 'development';

function requestId() {
  return typeof crypto.randomUUID === 'function'
    ? crypto.randomUUID()
    : crypto.randomBytes(16).toString('hex');
}

function statusPayload() {
  return {
    service: serviceName,
    message: 'Artifact promotion service is running',
    version,
    env: nodeEnv,
    hostname: os.hostname(),
    uptimeSeconds: Math.floor((Date.now() - startedAt) / 1000),
    timestamp: new Date().toISOString(),
  };
}

app.get('/', (req, res) => {
  res.type('html').send(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${serviceName}</title>
  <style>
    :root { color-scheme: dark; }
    body {
      margin: 0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial;
      background: radial-gradient(900px 500px at 20% 10%, #1D4F91 0%, transparent 60%),
                  radial-gradient(900px 500px at 80% 20%, #007CB0 0%, transparent 55%),
                  radial-gradient(900px 500px at 40% 90%, #86BC25 0%, transparent 55%),
                  #0b1020;
      color: #e8eefc;
      min-height: 100vh;
      display: grid;
      place-items: center;
      padding: 28px;
    }
    .card {
      width: min(900px, 100%);
      background: rgba(18, 25, 52, 0.72);
      border: 1px solid rgba(98, 181, 229, 0.25);
      border-radius: 18px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.35);
      overflow: hidden;
    }
    header {
      padding: 18px 22px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid rgba(187,189,191,0.18);
    }
    .badge {
      font-size: 12px;
      padding: 6px 10px;
      border-radius: 999px;
      background: rgba(134, 188, 37, 0.18);
      border: 1px solid rgba(134, 188, 37, 0.35);
      color: #d9ff9c;
      letter-spacing: 0.3px;
      white-space: nowrap;
    }
    main { padding: 18px 22px 22px; display: grid; gap: 14px; }
    .grid { display: grid; gap: 12px; grid-template-columns: repeat(12, 1fr); }
    .tile {
      grid-column: span 6;
      background: rgba(11, 16, 32, 0.55);
      border: 1px solid rgba(187,189,191,0.14);
      border-radius: 14px;
      padding: 14px 14px 12px;
    }
    @media (max-width: 720px) { .tile { grid-column: span 12; } }
    .k { color: rgba(232, 238, 252, 0.65); font-size: 12px; margin-bottom: 6px; }
    .v { font-size: 16px; font-weight: 650; }
    .muted { color: rgba(232, 238, 252, 0.7); font-size: 13px; line-height: 1.45; }
    .row { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }
    button {
      cursor: pointer;
      border: 1px solid rgba(98,181,229,0.25);
      background: rgba(0, 169, 224, 0.12);
      color: #e8eefc;
      padding: 10px 12px;
      border-radius: 12px;
      font-weight: 650;
    }
    button:hover { background: rgba(0, 169, 224, 0.18); }
    code {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono";
      font-size: 12px;
      background: rgba(187,189,191,0.10);
      padding: 2px 6px;
      border-radius: 8px;
      border: 1px solid rgba(187,189,191,0.12);
    }
    .okdot {
      width: 10px; height: 10px; border-radius: 50%;
      background: #86BC25; box-shadow: 0 0 18px rgba(134,188,37,0.55);
      display: inline-block;
    }
  </style>
</head>
<body>
  <div class="card">
    <header>
      <div>
        <div style="font-size:18px;font-weight:800;letter-spacing:0.2px">${serviceName}</div>
        <div class="muted">Live status pulled from <code>/api/status</code></div>
      </div>
      <div class="badge"><span class="okdot"></span> &nbsp;Healthy</div>
    </header>

    <main>
      <div class="grid">
        <div class="tile">
          <div class="k">Version</div>
          <div class="v" id="version">—</div>
        </div>
        <div class="tile">
          <div class="k">Environment</div>
          <div class="v" id="env">—</div>
        </div>
        <div class="tile">
          <div class="k">Uptime</div>
          <div class="v" id="uptime">—</div>
        </div>
        <div class="tile">
          <div class="k">Hostname</div>
          <div class="v" id="host">—</div>
        </div>
      </div>

      <div class="row">
        <button id="refresh">Refresh now</button>
        <span class="muted">Last updated: <code id="ts">—</code></span>
      </div>

      <div class="tile">
        <div class="k">Raw payload</div>
        <pre id="raw" style="margin:0;white-space:pre-wrap;word-break:break-word" class="muted">Loading…</pre>
      </div>
    </main>
  </div>

<script>
  const el = (id) => document.getElementById(id);

  function fmtUptime(seconds) {
    const s = Number(seconds || 0);
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const r = s % 60;
    return (h ? h + "h " : "") + (m ? m + "m " : "") + r + "s";
  }

  async function load() {
    const res = await fetch('/api/status', { cache: 'no-store' });
    const data = await res.json();

    el('version').textContent = data.version || '—';
    el('env').textContent = data.env || '—';
    el('uptime').textContent = fmtUptime(data.uptimeSeconds);
    el('host').textContent = data.hostname || '—';
    el('ts').textContent = new Date().toLocaleString();
    el('raw').textContent = JSON.stringify(data, null, 2);
  }

  el('refresh').addEventListener('click', load);
  load();
  setInterval(load, 5000);
</script>
</body>
</html>`);
});

app.get('/api/status', (req, res) => {
  res.set('Cache-Control', 'no-store');
  res.json({ ...statusPayload(), requestId: requestId() });
});

app.get('/healthz', (req, res) => {
  res.type('text').send('ok');
});

app.listen(port, () => {
  console.log(`[${serviceName}] listening on ${port} (version=${version}, env=${nodeEnv})`);
});
